name: neuroai-project13
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch>=2.4.0
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - neurogym==2.3.1
    - jupyter