name: neuroai-project13
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.3.1
    - numpy==1.26.4
    - scipy==1.13.1
    - matplotlib==3.9.2
    - seaborn==0.13.2
    - neurogym==2.3.1
    - jupyter