name: neuroai-project13
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pip:
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - neurogym==2.3.1
    - jupyter